// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezhjjjthvqhlotgnylab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aGpqanRodnFobG90Z255bGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzY2ODMsImV4cCI6MjA2ODQxMjY4M30.4fRKDsUY6jF3WasNdM5YfgsuXcxj8iH-g4dcUMy2-R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});